[versions]
acraCore = "5.13.1"
appcompat = "1.7.1"
constraintlayout = "2.2.1"
espressoCore = "3.7.0"
gradle = "9.0.1"
junit = "4.13.2"
junitVersion = "1.3.0"
material = "1.13.0"
preference = "1.2.1"
googleAuto = "1.1.1"

[libraries]
acra-core = { module = "ch.acra:acra-core", version.ref = "acraCore" }
acra-email = { module = "ch.acra:acra-mail", version.ref = "acraCore" }
appcompat = { module = "androidx.appcompat:appcompat", version.ref = "appcompat" }
constraintlayout = { module = "androidx.constraintlayout:constraintlayout", version.ref = "constraintlayout" }
espresso-core = { module = "androidx.test.espresso:espresso-core", version.ref = "espressoCore" }
ext-junit = { module = "androidx.test.ext:junit", version.ref = "junitVersion" }
gradle = { module = "com.android.tools.build:gradle", version.ref = "gradle" }
junit = { module = "junit:junit", version.ref = "junit" }
material = { module = "com.google.android.material:material", version.ref = "material" }
preference = { module = "androidx.preference:preference", version.ref = "preference" }
google-auto = { module = "com.google.auto.service:auto-service", version.ref = "googleAuto" }
google-auto-annotations = { module = "com.google.auto.service:auto-service-annotations", version.ref = "googleAuto" }